//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoạt động.
        /// </summary>
        public static string ActivedDisplay {
            get {
                return ResourceManager.GetString("ActivedDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sà lan.
        /// </summary>
        public static string Barge {
            get {
                return ResourceManager.GetString("Barge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sà lan nội bộ.
        /// </summary>
        public static string BargeCompany {
            get {
                return ResourceManager.GetString("BargeCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sà lan khách hàng.
        /// </summary>
        public static string BargeCustomer {
            get {
                return ResourceManager.GetString("BargeCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số sà lan.
        /// </summary>
        public static string BargeNumber {
            get {
                return ResourceManager.GetString("BargeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị vận chuyển.
        /// </summary>
        public static string BargeOwner {
            get {
                return ResourceManager.GetString("BargeOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trọng lượng hàng trong mức cho phép của xe!.
        /// </summary>
        public static string CanhBao2 {
            get {
                return ResourceManager.GetString("CanhBao2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa dữ liệu từ SAP.
        /// </summary>
        public static string CanNotDeleteSAPData {
            get {
                return ResourceManager.GetString("CanNotDeleteSAPData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể cập nhật dữ liệu từ SAP.
        /// </summary>
        public static string CanNotEditSAPData {
            get {
                return ResourceManager.GetString("CanNotEditSAPData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vật tư này đã có đơn trọng, không thể cập nhật đơn vị tính 2 rỗng..
        /// </summary>
        public static string CanNotUpdateUnitcodeEmpty {
            get {
                return ResourceManager.GetString("CanNotUpdateUnitcodeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chọn &quot;{0}&quot;!.
        /// </summary>
        public static string ChoiceRequired {
            get {
                return ResourceManager.GetString("ChoiceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &quot;{1}&quot; không tồn tại trong hệ thống..
        /// </summary>
        public static string CodeNotFound {
            get {
                return ResourceManager.GetString("CodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn xóa ?.
        /// </summary>
        public static string ConfirmDelContent {
            get {
                return ResourceManager.GetString("ConfirmDelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chắc chắn muốn xóa &quot;{0}&quot; &quot;{1}&quot;.
        /// </summary>
        public static string ConfirmDeleteData {
            get {
                return ResourceManager.GetString("ConfirmDeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xác nhận xóa.
        /// </summary>
        public static string ConfirmDelTitle {
            get {
                return ResourceManager.GetString("ConfirmDelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn có chắc muốn đóng SO ?..
        /// </summary>
        public static string ConfirmSOIsCompletedContent {
            get {
                return ResourceManager.GetString("ConfirmSOIsCompletedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian tạo.
        /// </summary>
        public static string CreatedTime {
            get {
                return ResourceManager.GetString("CreatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cung đường.
        /// </summary>
        public static string CungDuong {
            get {
                return ResourceManager.GetString("CungDuong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên cung đường.
        /// </summary>
        public static string CungDuongName {
            get {
                return ResourceManager.GetString("CungDuongName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng.
        /// </summary>
        public static string CustomerCode {
            get {
                return ResourceManager.GetString("CustomerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên Khách hàng.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không tồn tại không hệ thống..
        /// </summary>
        public static string DataNotFound {
            get {
                return ResourceManager.GetString("DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ..
        /// </summary>
        public static string DataNotValid {
            get {
                return ResourceManager.GetString("DataNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng OD.
        /// </summary>
        public static string DOQty {
            get {
                return ResourceManager.GetString("DOQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  &quot;{1}&quot; đã tồn tại trong hệ thống..
        /// </summary>
        public static string DuplicateCode {
            get {
                return ResourceManager.GetString("DuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vật tư &quot;{0}&quot;, mã khách hàng &quot;{1}&quot; đã tồn tại trong hệ thống..
        /// </summary>
        public static string DuplicateProductCodeCustomercode {
            get {
                return ResourceManager.GetString("DuplicateProductCodeCustomercode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi khi thao tác, vui lòng thử lại..
        /// </summary>
        public static string HasErrorWhenAction {
            get {
                return ResourceManager.GetString("HasErrorWhenAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu SAP.
        /// </summary>
        public static string isSAPData {
            get {
                return ResourceManager.GetString("isSAPData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian cập nhật cuối cùng.
        /// </summary>
        public static string LastEditedTime {
            get {
                return ResourceManager.GetString("LastEditedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin đăng nhập không chính xác.
        /// </summary>
        public static string LoginNotSuccess {
            get {
                return ResourceManager.GetString("LoginNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hàng hóa.
        /// </summary>
        public static string Merchandise {
            get {
                return ResourceManager.GetString("Merchandise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn trọng Min không thể lớn hơn đơn trọng Max.
        /// </summary>
        public static string MinSingleWeightNotLagerThanMaxSingleWeight {
            get {
                return ResourceManager.GetString("MinSingleWeightNotLagerThanMaxSingleWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập khẩu.
        /// </summary>
        public static string NhapKhau {
            get {
                return ResourceManager.GetString("NhapKhau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập Nội Địa.
        /// </summary>
        public static string NhapNoiDia {
            get {
                return ResourceManager.GetString("NhapNoiDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Vui lòng chọn ít nhất 1 &quot;{0}&quot; để xóa!&quot;.
        /// </summary>
        public static string NoChoiceError {
            get {
                return ResourceManager.GetString("NoChoiceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngừng hoạt động.
        /// </summary>
        public static string NonActivedDisplay {
            get {
                return ResourceManager.GetString("NonActivedDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu không trùng khớp.
        /// </summary>
        public static string PasswordNotEquals {
            get {
                return ResourceManager.GetString("PasswordNotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn tất.
        /// </summary>
        public static string PoCompleted {
            get {
                return ResourceManager.GetString("PoCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa hoàn tất.
        /// </summary>
        public static string PoUnCompleted {
            get {
                return ResourceManager.GetString("PoUnCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vật tư.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn trọng vật tư.
        /// </summary>
        public static string ProductAttribute {
            get {
                return ResourceManager.GetString("ProductAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã vật tư.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên vật tư.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhà cung cấp.
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhà cung cấp.
        /// </summary>
        public static string ProviderCode {
            get {
                return ResourceManager.GetString("ProviderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhà cung cấp.
        /// </summary>
        public static string ProviderName {
            get {
                return ResourceManager.GetString("ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập thông tin &quot;{0}&quot;!.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAP.
        /// </summary>
        public static string SAPData {
            get {
                return ResourceManager.GetString("SAPData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã cân 2 lần.
        /// </summary>
        public static string ScaleSecond {
            get {
                return ResourceManager.GetString("ScaleSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cân lần 1.
        /// </summary>
        public static string ScalesFirst {
            get {
                return ResourceManager.GetString("ScalesFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiểu cân.
        /// </summary>
        public static string ScaleTicketTypeCode {
            get {
                return ResourceManager.GetString("ScaleTicketTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàn tất.
        /// </summary>
        public static string SoComplete {
            get {
                return ResourceManager.GetString("SoComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng SO.
        /// </summary>
        public static string SOQty {
            get {
                return ResourceManager.GetString("SOQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa hoàn tất.
        /// </summary>
        public static string SoUnComplete {
            get {
                return ResourceManager.GetString("SoUnComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã Tick.
        /// </summary>
        public static string StatusIP {
            get {
                return ResourceManager.GetString("StatusIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa Tick.
        /// </summary>
        public static string StatusIPNo {
            get {
                return ResourceManager.GetString("StatusIPNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rơ moóc.
        /// </summary>
        public static string TrailersNumber {
            get {
                return ResourceManager.GetString("TrailersNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trong nước.
        /// </summary>
        public static string TrongNuoc {
            get {
                return ResourceManager.GetString("TrongNuoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính 2.
        /// </summary>
        public static string Unit2 {
            get {
                return ResourceManager.GetString("Unit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đơn vị tính.
        /// </summary>
        public static string UnitCode {
            get {
                return ResourceManager.GetString("UnitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đơn vị tính.
        /// </summary>
        public static string UnitName {
            get {
                return ResourceManager.GetString("UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Người dùng.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đang hoạt động.
        /// </summary>
        public static string UserActive {
            get {
                return ResourceManager.GetString("UserActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string UserAdmin {
            get {
                return ResourceManager.GetString("UserAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhập lại khẩu.
        /// </summary>
        public static string UserConfirmPassword {
            get {
                return ResourceManager.GetString("UserConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm cân.
        /// </summary>
        public static string UserData {
            get {
                return ResourceManager.GetString("UserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngừng hoạt động.
        /// </summary>
        public static string UserDeActive {
            get {
                return ResourceManager.GetString("UserDeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ tên.
        /// </summary>
        public static string UserFullName {
            get {
                return ResourceManager.GetString("UserFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tải khoản đã tồn tại.
        /// </summary>
        public static string UserNameExists {
            get {
                return ResourceManager.GetString("UserNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nhân viên thường.
        /// </summary>
        public static string UserNormal {
            get {
                return ResourceManager.GetString("UserNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản người dùng đã bị khóa..
        /// </summary>
        public static string UserNotActived {
            get {
                return ResourceManager.GetString("UserNotActived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mật khẩu.
        /// </summary>
        public static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Văn phong.
        /// </summary>
        public static string UserVanPhong {
            get {
                return ResourceManager.GetString("UserVanPhong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xe.
        /// </summary>
        public static string Vehicle {
            get {
                return ResourceManager.GetString("Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xe nội bộ.
        /// </summary>
        public static string VehicleCompany {
            get {
                return ResourceManager.GetString("VehicleCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xe khách hàng.
        /// </summary>
        public static string VehicleCustomer {
            get {
                return ResourceManager.GetString("VehicleCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khóa.
        /// </summary>
        public static string VehicleLock {
            get {
                return ResourceManager.GetString("VehicleLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số xe.
        /// </summary>
        public static string VehicleNumber {
            get {
                return ResourceManager.GetString("VehicleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị vận chuyển.
        /// </summary>
        public static string VehicleOwner {
            get {
                return ResourceManager.GetString("VehicleOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đơn vị vận chuyển.
        /// </summary>
        public static string VehicleOwnerCode {
            get {
                return ResourceManager.GetString("VehicleOwnerCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên đơn vị vận chuyển.
        /// </summary>
        public static string VehicleOwnerName {
            get {
                return ResourceManager.GetString("VehicleOwnerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không khóa.
        /// </summary>
        public static string VehicleUnlock {
            get {
                return ResourceManager.GetString("VehicleUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trọng lượng xe.
        /// </summary>
        public static string VehicleWeight {
            get {
                return ResourceManager.GetString("VehicleWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục kho.
        /// </summary>
        public static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã kho.
        /// </summary>
        public static string WarehouseCode {
            get {
                return ResourceManager.GetString("WarehouseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho nhập.
        /// </summary>
        public static string WarehouseEntry {
            get {
                return ResourceManager.GetString("WarehouseEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho xuất.
        /// </summary>
        public static string WarehouseExport {
            get {
                return ResourceManager.GetString("WarehouseExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên kho.
        /// </summary>
        public static string WarehouseName {
            get {
                return ResourceManager.GetString("WarehouseName", resourceCulture);
            }
        }
    }
}
